### ISSUE TITLE
CTRL+SHIFT+1 shortcut opens an empty translation box

### ISSUE THREAD

**Issue by nicorac** [itsecurityco/to-google-translate#105]
Steps to reproduce:
- select some text
- press CTRL+SHIFT+1
- translation page pops up, but left part is empty (does not contain the selected text)

Right click works correctly:
- select some text
- right-click on it, "To Google Translate", "Translate"
- translation page pops up with selected text correctly inserted in left part

FF 76.0.1 (x64), Win10-Pro-1903 (x64)

**Comment by itsecurityco** [comment]
Hello @nicorac ,

There is a lot of problems with the shortcuts I'm thinking in removing them because there is a lot of conflicts between operative systems. Maybe you can check out this thread, there is a way to customize your shortcuts in Firefox.

https://github.com/itsecurityco/to-google-translate/issues/69#issuecomment-599177230

Thank you

**Comment by nicorac** [comment]
> there is a way to customize your shortcuts in Firefox.

I'm an addon developer too, and I've never noticed that option.
It's simply great, thanks for pointing it out 👍

> There is a lot of problems with the shortcuts I'm thinking in removing them

Please don't 🙏.
Developers (like me) use the keyboard much more than the mouse, so I love having a shortcut for everything (it also helps me keep my brain in good shape 😂).
My suggestion is to not set a default shortcut (like uBlock Origin does), then change options page to show a hint text to let user open the shortcuts dialog and choose one.
Now, if they can't find an available one is not your problem anymore...
